Add the attestation module
blocky/nitriding pull request #12
Opened 2022-09-12 16:33 UTC by mwittie

This PR adds the `attestation` module with its `signature` submodule.

The `attestation` module provides two interfaces `Attester` and `Checker` to create and check attestations, following the white paper nomenclature.
There is also the `AttesterBuilder` interface, which we'll use later in the `ServerBuilder` (in a later PR).
There are two types of attesters: the `StandaloneAttester` uses a self-signed key and the `NitroAttester` uses the AWS NSM key to make attestations.

The `attestation/signature` module provides two interfaces `Signer` and `Verifier` to make and verify signatures over data.
There is also the `SignerBuilder` interface, which  w use to create an `AttesterBuilder`, since an `Attester` needs a `Signer`.
There are two types of signers: the `PSSSigner`, which the `Server` will use to create attestations, and the `BoxSigner`, which the server will use to exchange keys with other servers running on enclaves.

2022-09-13 21:06 UTC, ianhecker requested changes
reviewed, took about 3 hours from 1200-1500

have some concerns about:
1. missing checks for nil pointers and their potential to panic
2. copying test functions from another file into a testing function to pass them

have the suggestions of:
1. adding a custom Key type for [32]byte
2. clarity on the CBOR acronym
3. use of more embedding to shorten function calls
4. use of t.Run to shorten testing names and provide better readability
5. declaring multi-line variables outside of a mock for readability
6. using the embedded parlour suite functions
7. deleting an unneeded test file
8. clarifying duplicated formatted fmt.Errorf errors
9. breaking up GetAttestDoc() into helper functions
10. Adding helper functions for the `rand.Read` situation

2022-09-13 21:39 UTC, tahardi commented on attestation/checker.go
> +	CheckAttestBytes(attestBytes []byte) (*nitrite.Result, error)
Is `CheckAttestBytes` needed? I don't see it implemented by `nitro_checker` or `standalone_checker`

2022-09-13 21:39 UTC, tahardi commented on attestation/nitro_attester_test.go
> +func TestNitroAttesterBuilder_MakeAttester_HappyPath(t *testing.T) {
From what I've seen of the zpr codebase, we write one test function per function we wish to test and write each test case as a sub-test (like how you wrote `TestAttest()`). So, while not technically wrong, I think it would be nice to be consistent with the codebase.

*Not going to add the comments, but this applies to all of the other test files in this PR too*

2022-09-13 21:39 UTC, tahardi commented on attestation/nitro_attester_test.go
> +func TestMakeNitroAttester_HappyPath(t *testing.T) {
Another nit-picky formatting convention: Shouldn't this be `TestNitroAttester_MakeNitroAttester()` given that we follow the format `Test<module-name>_<function-name>`

*Not going to add the comments, but this applies to all of the other test files in this PR too*

2022-09-13 21:39 UTC, tahardi commented on attestation/nitro_attester_test.go
> +package attestation_test
You should add two additional test functions to test that `NitroAttester` and `NitroAttesterBuilder` adhere to the `Attester` and `AttesterBuilder` interfaces. Should look something like:

```golang
TestNitroAttester_Interfaces(t *testing.T) {
    session := nsm.Session{}
    signer := signature.PSSSigner{}
    var i interface{} = MakeNitroAttester(&session, signer)
    _, ok := i.(attestation.Attester)
    assert.True(t, ok, "NitroAttestor does not adhere to the Attester interface")
}
```

*Not going to add the comments, but this applies to all of the other test files in this PR too*

2022-09-13 21:39 UTC, tahardi commented on attestation/nitro_attester_test.go
> +func (p *NitroAttesterParlor) TestAttest() {
Shouldn't this be `TestNitroAttester_AttestDoc` instead of `TestAttest`?

2022-09-13 21:39 UTC, tahardi commented on attestation/nitro_checker_test.go
> +package attestation_test
Do we need this file? I don't remember seeing any like this in `zpr`---if there are no tests necessary then there isn't an accompanying test file

2022-09-13 21:39 UTC, tahardi commented on attestation/standalone_attester.go
> +	signer, err := builder.MakeSigner()
This is some new go syntactic sugar for me---the fact that you can just declare the type of interface you want in `StandaloneAttesterBuilder` without assigning it to any variable name---but noticed that you do two slightly different things between `standalone_attester.go` and `nitro_attester.go`. Namely, in `nitro_attester.go` you call `builder.SignerBuilder.MakeSigner()` whereas here you can skip the middle step and just call `builder.MakeSigner()`?

I assume both work, so would simply suggest you choose one syntax that is the same across both files (I prefer the longer one since it tells me where `MakeSigner()` resides). Same feedback applies to where you call `builder.MakePrivilegedCert()`

2022-09-13 21:39 UTC, tahardi commented on attestation/standalone_attester.go
> +		pcr := make([]byte, 48)
Got two magic numbers here. I think its worth adding a comment to explain what they are or just making two variables with names to indicate what they are

2022-09-13 21:39 UTC, tahardi commented on attestation/standalone_attester.go
> +		ModuleID:    "i-0e811925634bbd863-enc018274a97f16d616",
magic string. What is this and where does it come from? This is never going to change?

2022-09-13 21:52 UTC, tahardi commented
I don't understand why we need to sign the user data since it is already being signed by the attestation process and thus tied to our Nitro enclave.

I don't know the fine details of Nitro, but at least in SGX attestations are signed by keys specific to a hardware platform and enclave instance. Thus, if you included user data in that attestation, the user data is tied to that signature as well. Is this not the case for Nitro? Seems redundant to have our enclave program generate a key pair to sign the user data only to then have it generate an attestation that is signed by a key pair already unique to the enclave/hardware platform.

2022-09-14 23:36 UTC, tahardi commented on attestation/signature/box_signer.go
> +}
I'm wondering if this struct is really needed. It only appears to be used by `BoxVerifier` and very lightly at that. The `BoxSigner` struct just declares `pubKey *[boxKeyLen]byte` and i think it would be fine to do the same in `BoxVerifier` but with an additional variable for the private key.

If you don't want to get rid of it, I would at least suggest moving `boxKey` and `NewBoxKey()` to `box_verifier.go` since that is where they are used.

2022-09-14 23:36 UTC, tahardi commented on attestation/signature/box_signer.go
> +	)
How does this function work? I would assume you need a private key to sign, not public, but there doesn't seem to be any setup in this file where you give it a private key to use. In fact, i was confused when I saw that verify took a public and private because, again, my understanding was that you only need a public key to verify a signature.

EDIT: So, I just looked at `pss_signer.go` and these two signers appear to be taking opposite approaches to signing---is that intended? More specifically, `pss_signer.go` is actually signing data with a private key and then verifying it against a public key, whereas `box_signer.go` appears to be using `Sign` to encrypt data with a public key such that only the private key holder can than verify it (i.e., decrypt it) similar to what happens during a key-sharing protocol.

2022-09-14 23:36 UTC, tahardi commented on attestation/signature/box_signer.go
> +func (s BoxSigner) ParsePublicKey(keyBytes []byte) (any, error) {
I'm confused by this function because it is called "ParsePublicKey" but from what I can tell all it does is create a copy of the incoming key and does not modify it at all.

2022-09-15 00:05 UTC, tahardi commented
Sill a little confused by the GitHub PR interface and where these comments go, but hopefully my feedback is helpful! Overall good job---I think the interfaces and use of builders make everything very clean.

2022-09-16 17:05 UTC, mwittie commented on Makefile
> +	@mockery --all
Thanks!

2022-09-16 17:06 UTC, mwittie commented on attestation/attester.go
> +	GetAttestDoc(nonce, userData []byte) (attestDoc Doc, err error)
I think that sometimes we do need to name the returns and so I like to do that in interfaces for consistency.

2022-09-16 17:10 UTC, mwittie commented on attestation/doc.go
> +	CBOR []byte `json:"CBOR"`
Yeah, CBOR stands for Consistent Binary Object Representation https://cbor.io/. It's a bit like TCP (Transmission Control Protocol) - a concept that is better known by its acronym than its expansion.
In this case I think it makes sense to stay with `CBOR` as the name. That's how the code from Brave uses it as well.
Having said that, I do like the pattern of adding extra types to show to document the expansion. I'll keep that in mind.

2022-09-16 17:11 UTC, mwittie commented on attestation/nitro_attester.go
> +	signer, err := builder.SignerBuilder.MakeSigner()
Yeah, good point!

Changed.

2022-09-16 17:15 UTC, mwittie commented on attestation/nitro_attester.go
> +	if res.Attestation == nil || res.Attestation.Document == nil {
Thanks!

2022-09-16 17:26 UTC, mwittie commented on attestation/nitro_attester.go
> +func (attester NitroAttester) GetAttestCert() (certificate.PrivilegedCert, error) {
@ianhecker yes, this is the permanent return for `NitroAttester.GetAttestCert()`. I thought about other approaches like making a subinterface, or actually returning the cert after getting it from Amazon. In the end I thought that the attester should support this function and that a user should get an error when calling it that tells it to get the AWS cert from out of band.

Having said that, I updated the error message to tell the user where specifically to get the AWS certificate.

2022-09-16 17:34 UTC, mwittie commented on attestation/nitro_attester_test.go
> +package attestation_test
I think that's a good suggestion. I don't know, I think I was trying to keep the tests separately readable without using a common `initMocks` function or going all the way to `Parlor` tests.
Grouping cases with `t.Run` does make things more readable though. I'll convert.

2022-09-16 17:45 UTC, mwittie commented on attestation/nitro_attester_test.go
> +	nsmSession          *mocks.NSMSession
Reordered.

2022-09-16 17:50 UTC, mwittie commented on attestation/nitro_attester_test.go
> +		p.nsmSession.On(
Good suggestion

2022-09-16 17:51 UTC, mwittie commented on attestation/nitro_attester_test.go
> +		assert.NoError(p.T(), err)
@ianhecker I actually like the current style better for two reasons:
1. it allows easier conversion between test types
2. it makes tests more readable through consistent syntax

2022-09-16 17:55 UTC, mwittie commented on attestation/nitro_checker_test.go
> +//Note: no additional tests are necessary for NitroChecker
done

2022-09-16 18:24 UTC, mwittie commented on attestation/signature/box_signer.go
> +	return &pubKey, nil
Well, the call 
```
sig, err := box.SealAnonymous(
		out,
		data,
		s.pubKey,
		cryptoRand.Reader,
	)
```
takes in a `*[32]byte` as the pubKey argument, so I thought I would just stay with that type.

I did the conversions

2022-09-16 18:58 UTC, mwittie commented on attestation/signature/box_verifier.go
> +	return BoxVerifier{key: key}
addressed

2022-09-16 18:59 UTC, mwittie commented on attestation/signature/box_verifier.go
> +		v.key.PubKey,
fixed

2022-09-16 19:00 UTC, mwittie commented on attestation/signature/box_verifier_test.go
> +	TestBoxSigner_Sign_HappyPath(t)
I duplicated the code

2022-09-16 19:37 UTC, mwittie commented on attestation/signature/pss_signer.go
> +	return PSSSigner{privateKey: privateKey}
done

2022-09-16 19:41 UTC, mwittie commented on attestation/signature/pss_signer.go
> +	return x509.MarshalPKCS1PublicKey(&s.privateKey.PublicKey)
Addressed. Thanks for catching all these problems. I'm converting to passing structures unless absolutely necessary to pass pointers. We can deal with any potential performance issues later, but it will avoid these types of errors as well as more complicated testing.

2022-09-16 20:10 UTC, mwittie commented on attestation/signature/pss_signer_test.go
> +	"github.com/stretchr/testify/assert"
Done

2022-09-16 20:14 UTC, mwittie commented on attestation/signature/pss_verifier.go
> +		return nil, fmt.Errorf("%v: %w", ErrBadSignature, err)
done

2022-09-16 20:14 UTC, mwittie commented on attestation/signature/pss_verifier_test.go
> +	TestPSSSigner_Sign_HappyPath(t)
copied

2022-09-16 20:15 UTC, mwittie commented on attestation/signature/box_signer.go
> +	cryptoRand "crypto/rand"
removed - that was leftover from Brave code

2022-09-16 20:48 UTC, mwittie commented on attestation/signature/verifier.go
> +	ErrBadSignature = "failed to verify signature"
done

2022-09-18 21:45 UTC, mwittie commented on attestation/standalone_attester.go
> +	signer signature.Signer
Embedding makes the embedded objects public. If I do
```
type StandaloneAttester struct {
	signature.Signer
	...
}
```
then someone could do 
```
attester := StandaloneAttester{}
attester.Signer = a different signer
```
or
```
attester.Sign(...)
```
Without embedding I'm not forced to expose more functionality than I intend to.

2022-09-19 00:05 UTC, mwittie commented on attestation/standalone_attester.go
> +	coseHeader := nitrite.CoseHeader{Alg: cose.AlgorithmES384}
yeah, I straight up forgot to test this with mocks... Done.

2022-09-19 00:07 UTC, mwittie commented on attestation/standalone_attester_test.go
> +func TestStandaloneAttesterBuilder_MakeAttester_SignerBuilderError(
done

2022-09-19 00:16 UTC, mwittie commented on attestation/standalone_attester_test.go
> +	nonce := make([]byte, 20)
done

2022-09-19 00:16 UTC, mwittie commented on attestation/standalone_attester_test.go
> +	assert.Equal(t, nonce, doc.Document.Nonce)
done

2022-09-19 02:27 UTC, mwittie commented on attestation/standalone_checker.go
> +		Roots:               c.roots,
It does not, since we're using a self-signed certificate in the attester. The certificate gets embedded in the attestation document and since it's a CA certificate, it does not need other roots. I added a test to show this
```
	t.Run("empty roots", func(t *testing.T) {
		attester, err := attestation.StandaloneAttesterBuilder{
			PrivilegedCertBuilder: certificate.BasePrivilegedCertBuilder{},
			SignerBuilder:         signature.PPSSignerBuilder{KeyLen: 1024},
		}.MakeAttester()
		assert.NoError(t, err)
		require.NotNil(t, attester)

		nonce := nitridingtest.MakeRandBytes(t, 20)
		userData := nitridingtest.MakeRandBytes(t, 20)

		attest, err := attester.GetAttestDoc(nonce, userData)
		assert.NoError(t, err)

		checker := attestation.StandaloneChecker{}
		res, err := checker.CheckAttestDoc(attest)
		require.NoError(t, err)
		assert.NotNil(t, res)
	})
```
More broadly though the `roots` in options get used to verify a certificate. If the roots are missing, nil is OK, then the certificate simply fails to verify.

2022-09-19 02:32 UTC, mwittie commented on attestation/checker.go
> +	CheckAttestBytes(attestBytes []byte) (*nitrite.Result, error)
Good catch! Leftover from earlier code. I removed.

2022-09-19 02:32 UTC, mwittie commented on attestation/nitro_attester_test.go
> +func TestNitroAttesterBuilder_MakeAttester_HappyPath(t *testing.T) {
I revised the testing format

2022-09-19 02:38 UTC, mwittie commented on attestation/nitro_attester_test.go
> +func TestMakeNitroAttester_HappyPath(t *testing.T) {
I don't think so. `MakeNitroAttester()` does not belong to the `NitroAttester` struct. I could name the test `TestAttestation_MakeNitroAttester_HappyPath`, but its already clear we're testing `attestation` functions since the package is `attestation_test`.

That's also how Goland suggests autocompletion
![image](https://user-images.githubusercontent.com/5369629/190941582-f2d4feb9-f55c-49c1-9dbd-03b84b52d4d8.png)

2022-09-19 15:44 UTC, mwittie commented on attestation/nitro_attester_test.go
> +package attestation_test
Oh yeah, I forgot we decided to do that! Here's a way to simplify the test.
```
func TestNitroAttester_Interfaces(t *testing.T) {
	var i interface{} = attestation.NitroAttester{}
	_, ok := i.(attestation.Attester)
	assert.True(t, ok)
}
```

Or with a function:
```
func AttestType[T any](t *testing.T, obj any) {
	_, ok := obj.(T)

	assert.Truef(
		t,
		ok,
		"obj of type %#v is not %v",
		obj,
		reflect.TypeOf((*T)(nil)).String()[1:],
	)
}

func TestNitroAttester_Interfaces(t *testing.T) {
	nitridingtest.AttestType[attestation.Attester](t, attestation.NitroAttester{})
}
```

2022-09-19 16:04 UTC, mwittie commented on attestation/nitro_attester_test.go
> +func (p *NitroAttesterParlor) TestAttest() {
done

2022-09-19 16:05 UTC, mwittie commented on attestation/nitro_checker_test.go
> +package attestation_test
yeah, I wanted to make clear there there weren't going to be any tests and that I didn't just forget to test `NitroChecker`. I got the same comment from Ian and removed the file.

2022-09-19 16:17 UTC, mwittie commented on attestation/standalone_attester.go
> +	signer, err := builder.MakeSigner()
@tahardi There's a subtle semantic difference there. 

```golang
type StandaloneAttesterBuilder struct {
	certificate.PrivilegedCertBuilder
	signature.SignerBuilder
}
```
means that a `StandaloneAttesterBuilder` is also a `signature.SignerBuilder`. So, in a receiver function for `builder StandaloneAttesterBuilder` you can then say
```golang
builder.MakeSigner()
```
or
```golang
builder.SignerBuilder.MakeSigner()
```

On the other hand, when
```golang
type StandaloneAttester struct {
	signer signature.Signer
	cert   certificate.PrivilegedCert
	helper AttesterHelper
}
```
a `StandaloneAttester` has a `signer` of type `signature.Signer`. Given a receiver function for `attester StandaloneAttester` you can say
```golang
attester.signer.Sign(...)
```
but not
```golang
attester.Sign(...)
```
nor
```golang
attester.Signer.Sign(...)
```
Embedding an object instance, as in this case the `signer` makes its functionality private to the `attester` and doesn't expose any of the `signer` functions. It also means someone can't do
```golang
attester.Signer = nil
```

2022-09-19 16:26 UTC, mwittie commented on attestation/standalone_attester.go
> +		pcr := make([]byte, 48)
Good point, I'll add a comment

2022-09-19 16:29 UTC, mwittie commented on attestation/standalone_attester.go
> +		ModuleID:    "i-0e811925634bbd863-enc018274a97f16d616",
I'll add a comment

2022-09-19 17:07 UTC, mwittie commented on attestation/signature/box_signer.go
> +}
I moved the BoxKey functionality to `box_key.go` to separate it out. Then I defined
```golang
const BoxKeyLen = 32

type BoxKey [BoxKeyLen]byte
type BoxPublicKey struct {
	BoxKey
}
type BoxPrivateKey struct {
	BoxKey
}
type BoxKeyPair struct {
	PublicKey  *BoxPublicKey
	PrivateKey *BoxPrivateKey
}
```
to make the types more explicit. 

I do want to keep the `BoxKeyPair` to know which keys should go together and to do the conversion from `BoxKey` to `BoxPublicKey` and `BoxPrivateKey`

2022-09-19 17:22 UTC, mwittie commented on attestation/signature/box_signer.go
> +	)
Yeah, these signers do different things. The `PSSSigner` is that you would expect - signs data with the private key. That is the signer we use when making attestations.
The `BoxSigner` can `sign` with the public key. We'll use it when exchanging keys between enclaves. Brave uses something like the BoxSigner in their code, so this is just getting the stuff they need to work within our interface definitions.

2022-09-19 17:24 UTC, mwittie commented on attestation/signature/box_signer.go
> +func (s BoxSigner) ParsePublicKey(keyBytes []byte) (any, error) {
Now it does a little bit more, in that it checks length. The function really converts key in `[]byte` to a particular publickey type, regardless of the `[]byte` representation.

2022-09-20 19:16 UTC, tahardi commented on attestation/standalone_attester_test.go
> +	require.NotNil(p.T(), coseHeaderBytes)
Throw a newline in after each iniatialization/require check for readability? For example

```golang
coseHeaderBytes, err := helper.MarshalCBOR(coseHeader)
require.NoError(p.T(), err)
require.NotNil(p.T(), coseHeaderBytes)

pcrs, err := helper.MakePCRs()
require.NoError(p.T(), err)
require.NotNil(p.T(), pcrs)
```

2022-09-20 19:16 UTC, tahardi commented on certificate/privileged_cert_test.go
>  func TestMakeBasePrivilegedCert_HappyPath(t *testing.T) {
Just `TestMakeBasePrivilegedCert`. Also, there are some places where `MakeBasePrivilegedCert` can return an err. Maybe you should check those cases as well

2022-09-20 21:39 UTC, mwittie commented on attestation/attester_helper_test.go
> +func TestBaseAttesterHelper_MarshalCBOR_HappyPath(t *testing.T) {
OK, I removed the `HappyPath` suffix if we only have one test for the function.
As far as other test cases, its hard to trigger errors in `Marshal` or `Rand` functions and historically we haven't done that.
Part of the reason for writing the `AttesterHelper` interface is wrap these calls so that we can mock them in `GetAttestDoc`, but the abstraction recursion has to stop somewhere :)

2022-09-20 21:48 UTC, mwittie commented on attestation/signature/box_key_test.go
> +func TestBoxKey_ToConstSlicePtr_HappyPath(t *testing.T) {
I did that for all

2022-09-20 21:57 UTC, mwittie commented on attestation/signature/box_signer_test.go
> +func TestBoxSigner_Sign_HappyPath(t *testing.T) {
Done

2022-09-20 22:01 UTC, mwittie commented on attestation/signature/pss_signer_test.go
> +func TestPSSSigner_MarshalPublicKey_HappyPath(t *testing.T) {
done

2022-09-20 22:01 UTC, mwittie commented on attestation/signature/box_signer_test.go
> +func TestBoxSigner_MarshalPublicKey_HappyPath(t *testing.T) {
done

2022-09-20 22:03 UTC, mwittie commented on attestation/standalone_attester_test.go
> +	require.NotNil(p.T(), coseHeaderBytes)
done

2022-09-20 22:04 UTC, mwittie commented on certificate/privileged_cert_test.go
>  func TestMakeBasePrivilegedCert_HappyPath(t *testing.T) {
done

2022-09-20 22:07 UTC, mwittie commented on certificate/privileged_cert_test.go
>  func TestMakeBasePrivilegedCert_HappyPath(t *testing.T) {
In this case I don't think its worth to mock all the internal calls. We cover our bases through the happy path test and through fuzzing.

2022-09-20 22:59 UTC, tahardi approved these changes
I don't actually know how to approve on GitHub. I think I have to submit this comment and select the "approve" radial button. Let's find out...

2022-09-21 23:09 UTC, merged