Feature/tls
blocky/nitriding pull request #17
Opened 2022-10-17 18:08 UTC by mwittie

This PR adds the tools needed by the `nitriding` `server` (future PR) to get certificates to create TLS connections.

2022-10-17 18:13 UTC, mwittie commented on common.go
> +type Builder[T any] interface {
This is a very high level interface and I'm not sure where to put it. I looked around for some options and it looks like packages like `utils or `models` are discouraged. So I just put it at the top level, but I'm open to suggestions.

2022-10-17 18:19 UTC, mwittie commented on server/tls.go
> +
I'm not closing the errChan since I expect Start to run forever an alternative is to pass in the errChan as a field in builder, but I think this is good tradeoff from usability perspective and error checking

2022-10-17 18:20 UTC, mwittie commented on server/tls_test.go
> +		certMgrBuilder.On("Build").Return(certificate.ACMECertMgr{}, nil)
I couldn't figure out how to pass in a `chan error` as a parameter into the `certMgr.Start(errChan)` call in a way that I can then send to it to force an error. Instead, I'm passing in a zero value `ACMECertMgr` that I know will create an error.

2022-10-18 15:12 UTC, dlm requested changes
this is a test

2022-10-18 19:58 UTC, tahardi approved these changes
Looks good to me! But I also don't understand how this will fit into the larger system so would recommend you wait on Dave's approval too

2022-10-18 19:58 UTC, tahardi commented on server/tls.go
> +			tlsBundle.cert, err = tlsBundle.GetCachedCert(5 * time.Minute)
5 minutes seems excessive, no?

2022-10-18 19:58 UTC, tahardi commented on server/tls.go
> +		for {
This is a potentially endless loop if we just keep getting `ErrGetCertFromCache`, right? Is that ok (i.e., intended)?

2022-10-19 17:02 UTC, dlm approved these changes
A few comments, but nothing that should be too hard to address... but let me know if you want me to take another look at anything.

2022-10-20 00:08 UTC, mwittie commented on server/tls_test.go
> +		certBuilder.On("Build").Return(nilCert, expErr)
Done https://github.com/vektra/mockery/issues/513

2022-10-20 00:11 UTC, mwittie commented on common.go
> +type Builder[T any] interface {
moved to package `common`

2022-10-20 00:13 UTC, mwittie commented on certificate/manager.go
> +	ErrMakeCert         = "could make a certificate from PEM bytes"
good catch!

2022-10-20 00:31 UTC, mwittie commented on certificate/manager.go
> +func (certMgr ACMECertMgr) GetCert(
Removed nil checks and added an internal test to make sure that internal fields are not nil on object creation.

2022-10-20 00:38 UTC, mwittie commented on server/tls.go
> +			tlsBundle.cert, err = tlsBundle.GetCachedCert(5 * time.Minute)
Well, I don't actually know. Then we're calling `tlsBundle.certMgr.GetCert` underneath it starts talking to Let's Encrypt servers. I've seen this take several seconds under normal operation. I think a long timeout doesn't hurt anything.

2022-10-20 00:46 UTC, mwittie commented on server/tls.go
> +	timeout time.Duration,
Yeah, this is a bit tricky. The way that Brave wrote this is for `GetCert` to keep retrying until it gets a cert, or errors through something other than timeout. They were creating the context with timeout in the for loop can calling `defer cancel()` right away. The problem is that defer gets called only at the end of the function and so in practice it cancels only the latest context. The other eventually time out, but we have temporary resource leak until they do. To avoid this issue I moved the context creation to its own function so that defer can act there on every context with timeout around `tlsBundle.certMgr.GetCert`. @dlm thoughts?

2022-10-20 16:20 UTC, mwittie commented on server/tls.go
> +		for {
OK, good call, I added a context to `GetCert()`

2022-10-21 15:56 UTC, mwittie commented on certificate/manager.go
> +func (certMgr ACMECertMgr) GetCert(
OK, I'm actually going back on this. I think it's too easy to pass in an empty struct that contains nil pointers and so I put back the nil checks and the corresponding tests.
I wanted to use dig, but there is only one possible nil in the dereference chain, so I think it's cleaner to just use ifs (ugh).

2022-10-21 16:11 UTC, mwittie commented on server/tls.go
> +var CertCacheRetryDelay = time.Second
done

2022-10-21 16:20 UTC, mwittie commented on certificate/manager.go
> +	acmeCertCacheDir = "cert-cache"
done

2022-10-21 17:36 UTC, mwittie commented on server/tls.go
> +	timeout time.Duration,
Changed to `getCachedCert` and testing internally

2022-10-21 18:03 UTC, merged