Feature/refactor nitriding
blocky/nitriding pull request #8
Opened 2022-08-11 00:12 UTC by mwittie

This PR adds the ability to generate attestations based on the new interfaces. There is still a low of upstream code that needs to be refactored, so I'm simply plugging in our interfaces where necessary, but leaving other code unchanged.

2022-08-16 15:52 UTC, ianhecker requested changes

2022-08-17 17:05 UTC, dlm reviewed
I made it though the attestation package.  There are a lot of comments that correspond more broadly to the entire project.  Let's get those comments addressed (and fixed up across the project) and then we can take another pass

2022-08-22 22:43 UTC, mwittie commented on example/main_test.go
> +	assert.NoError(t, err)
done

2022-08-22 22:50 UTC, mwittie commented on attestation/verifier.go
> +func (v JSONVerifier) Verify(signedDataBytes []byte) (SignedData, error) {
done

2022-08-22 22:50 UTC, mwittie commented on attestation/signer_test.go
> +	_, err := rand.Read(data)
replaced with fuzzing

2022-08-22 22:50 UTC, mwittie commented on attestation/signer.go
> +	PublicKey() *rsa.PublicKey
updated

2022-08-22 22:51 UTC, mwittie commented on attestation/signer.go
> +type Signer interface {
done

2022-08-22 22:51 UTC, mwittie commented on attestation/signer_test.go
> +func TestJSONSigner_HappyPath(t *testing.T) {
Renamed

2022-08-22 22:52 UTC, mwittie commented on attestation/checker_test.go
> +	_, err = attestation.MakeStandaloneChecker(fileName)
done

2022-08-22 22:56 UTC, mwittie commented on attestation/checker_test.go
> +	assert.NoError(t, err)
addressed

2022-08-22 22:58 UTC, mwittie commented on attestation/checker_test.go
> +func TestMakeStandaloneChecker_BadCertFile(t *testing.T) {
solved

2022-08-22 22:58 UTC, mwittie commented on attestation/checker_test.go
> +func TestStandaloneChecker_CannotVerify(t *testing.T) {
fixed

2022-08-22 22:58 UTC, mwittie commented on attestation/checker.go
> +func MakeStandaloneChecker(rootCertFile string) (StandaloneChecker, error) {
passing in a file, not a string now

2022-08-22 23:00 UTC, mwittie commented on attestation/checker.go
> +	CheckAttestation(attest Attestation) (*nitrite.Result, error)
the two checkers behave pretty differently now, so I think the interface still makes sense

2022-08-22 23:00 UTC, mwittie commented on attestation/checker.go
> +	attestDoc, err := base64.StdEncoding.DecodeString(string(attest))
solved

2022-08-22 23:03 UTC, mwittie commented on attestation/attester_test.go
> +func TestStandaloneAttester_HappyPath(t *testing.T) {
changed how the cert file gets passed around and cleaned up

2022-08-22 23:03 UTC, mwittie commented on attestation/attester.go
> +	certFile   string
yes

2022-08-22 23:05 UTC, mwittie commented on attestation/attester.go
> +type Attester interface {
It does have a session, which is why I added the close function. Open to suggestions

2022-08-22 23:06 UTC, mwittie commented on attestation/attester.go
> +		return "", err
Its a string, but I made `Attestation` conform to the stringer interface, so we don't have to cast it anymore

2022-08-22 23:06 UTC, mwittie commented on attestation/attester.go
> +	privateKey *rsa.PrivateKey
addressed

2022-08-22 23:09 UTC, mwittie commented on attestation.go
> +	"github.com/blocky/nitrite"
nitrite is not a part of this repo and following our earlier discussion I didn't want to embed a nitrite submodule. So, without a submodule, I think this is the alternative of getting the right version of the code into the project.

2022-08-22 23:31 UTC, closed without merging